# Pipelines to test code

stages:
  # Install testing tools into extra container to speed up later testing steps
  - container_testing
  - test
  - deploy
  - bots

# ==================================================================================================
# ===== Stage: Container ===========================================================================

# Use anchors to reuse parts for the different steps
.stage_container_anchor: &container_anchor
  image: "quay.io/buildah/stable"
  variables:
    # Use vfs with buildah. Docker offers overlayfs as a default, but buildah
    # cannot stack overlayfs on top of another overlayfs filesystem.
    STORAGE_DRIVER: "vfs"
    BUILDAH_FORMAT: "oci"
  before_script:
    # Print out program versions for debugging
    - buildah version
    - buildah login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"

testing_image:
  <<: *container_anchor
  stage: container_testing
  variables:
    # Set base image variables here because it didn't work to set them in the anchor
    IMAGE_TAG: "testing_ocp"
    FULL_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}/${IMAGE_TAG}"
    IMAGE_FILE: "tests/dockerfile"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_REF_SLUG == "main" || $CI_COMMIT_REF_SLUG == "develop" || $CI_COMMIT_REF_NAME =~ /^containerbuild/'
      # Run only for important branches or if the branch name starts with the 'containerbuild'
      # keyword, else every new branch would start to build this container
      changes:
        - tests/dockerfile
        - .gitlab-ci.yml
        - pyproject.toml
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual
      allow_failure: true
    - when: never
  script:
    # Build image, using layers=false squashes only new layers,
    # but this reduces space usage while building and is much faster
    - echo "buildah bud --layers=false --squash -f ${IMAGE_FILE} -t ${IMAGE_TAG} ."
    - buildah bud --layers=false --squash -f ${IMAGE_FILE} -t ${IMAGE_TAG} .
    - buildah tag ${IMAGE_TAG} ${FULL_IMAGE_NAME}
    - buildah images
    # Push images only from main and develop branches to reduce space usage
    - if [[ "${CI_COMMIT_REF_SLUG}" == "main" ]] || [[ "${CI_COMMIT_REF_SLUG}" == "develop" ]]; then buildah push ${FULL_IMAGE_NAME}; fi

# ==================================================================================================
# ===== Stage: Test ================================================================================

# Use anchors to reuse parts for the different steps
.stage_test_anchor: &test_anchor
  variables:
    IMAGE_TAG: "testing_ocp"
    # Use the main repository's container image by default except for specific branch names
    FULL_IMAGE_NAME: "registry.gitlab.com/opencodepapers/opencodepapers/main/${IMAGE_TAG}"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: $CI_COMMIT_REF_SLUG == "develop"
      variables:
        FULL_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}/${IMAGE_TAG}"
    - when: always
  image: ${FULL_IMAGE_NAME}

linting:
  <<: *test_anchor
  stage: test
  script:
    - isort --check-only --diff .
    - black --check --diff .
    - npx /usr/app/node_modules/prettylint/bin/cli.js \
      $(find . -type f \( -name '*.md' -o -name '*.yml' -o -name '*.yaml' \) ! -path './.*/*' ! -path './dataset/*')
    - pylint --disable=import-error --disable=parse-error $(find . -type f -name "*.py")
    - flake8 .

validate_data:
  <<: *test_anchor
  stage: test
  script:
    - python3 tests/test_benchmark_files.py

analysis:
  <<: *test_anchor
  stage: test
  # The following pipe allows using a ':' in the 'sed' command, also remove the '-' list indicator
  script: |
    mkdir ./badges/
    radon cc -a . | tee ./badges/radon.log
    RCC_SCORE=$(sed -n 's/^Average complexity: \([A-F]\) .*/\1/p' ./badges/radon.log)
    anybadge --label=complexity --file=badges/rcc.svg --overwrite --value=$RCC_SCORE A=green B=yellow C=orange D=red E=red F=red
    echo "Radon cyclomatic complexity score is: $RCC_SCORE"
    pygount --format=summary ./
  artifacts:
    paths:
      - ./badges/

# ==================================================================================================
# ===== Stage: Deploy ==============================================================================

pages:
  <<: *test_anchor
  stage: deploy
  script:
    - python3 website/build_tasks_data.py
    - python3 website/build_website_bench.py
    - python3 website/build_website_tasks.py
    - python3 website/build_website_papers.py
    # Badges
    - python3 extras/badges/generate_badges.py
    - python3 extras/badges/make_file_overview.py
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

# ==================================================================================================
# ===== Stage: Bots ================================================================================

merge_bot:
  stage: bots
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never
  variables:
    IMAGE_TAG: "testing_ocp"
    FULL_IMAGE_NAME: "registry.gitlab.com/opencodepapers/opencodepapers/main/${IMAGE_TAG}"
    GITLAB_TOKEN: "$BOT_TOKEN"
    PROJECT_ID: "$CI_PROJECT_ID"
    TARGET_FOLDER: "dataset/benchmarks/"
    SQUASH_COMMITS: "1"
  image: ${FULL_IMAGE_NAME}
  script:
    - python3 tests/bot_merge_automatic.py
  allow_failure: false
  interruptible: true
