# Runs the data tests.

name: validate_data

on:
  workflow_call:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: registry.gitlab.com/opencodepapers/opencodepapers/main/testing_ocp
    steps:
      - uses: actions/checkout@v4
      - run: python3 tests/test_benchmark_files.py
